---
title: CatSource
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  images:
    title: Images
    output: true
collections_dir: content
name: CatSource
description: Tutorials, resources and more, for Scratchers, by Scratchers.
logo: logo.svg
footer-links:
  github: csourcesc
  rss: "/feed.xml"
comments: true
url: https://csourcesc.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
feed:
  url: 'https://csourcesc.github.io/feed.xml'
