---
title: CatSource Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: CatSource Blog
description: Offical blog for CatSource
logo: logo.svg
footer-links:
  github: csourcesc
  rss: "/feed.xml"
disqus: 
url: csourcesc.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
